[project]
name = "version-checker"
version = "0.1.0"
description = ""
authors = [
    { name = "Lei.Lee", email = "codeplus@qq.com" }
]
license = { text = "MIT" }
readme = "README.md"
packages = [{ include = "app" }]
package-mode = false
requires-python = ">=3.12,<4.0"
dependencies = [
    "aiofiles (>=24.1.0,<25.0.0)",
    "aiohttp (>=3.11.11,<4.0.0)",
    "arrow (>=1.3.0,<2.0.0)",
    "beautifulsoup4 (>=4.12.3,<5.0.0)",
    "click (>=8.1.8,<9.0.0)",
    "html5lib (>=1.1,<2.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "lxml (>=5.3.0,<6.0.0)",
    "pydantic (>=2.10.4,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "semver (>=3.0.2,<4.0.0)",
    "retrying (>=1.3.4,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[tool.poetry.scripts]
version-checker = "app.cli:start"
