[project]
requires-python = "^3.12"

[tool.poetry]
name = "version-checker"
version = "1.0.0"
description = "Here is the description of the project."
authors = ["Lei.Lee <codeplus@qq.com>"]
license = "MIT"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
aiofiles = "^23.2.1"
aiohttp = "^3.9.5"
arrow = "^1.3.0"
beautifulsoup4 = "^4.12.3"
click = "^8.1.7"
html5lib = "^1.1"
loguru = "^0.7.2"
lxml = "^5.2.1"
pydantic = "^2.7.1"
python-dotenv = "^1.0.1"
requests = "^2.31.0"
semver = "^3.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
version-checker = "app.cli:start"
