[app]
title = "Software version checker"

[[softwares]]
name = "git"
repo = "git/git"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://kernel.org/pub/software/scm/git/git-{version}.tar.gz",
    "https://kernel.org/pub/software/scm/git/git-htmldocs-{version}.tar.gz",
    "https://kernel.org/pub/software/scm/git/git-manpages-{version}.tar.gz",
]

[[softwares]]
name = "clash_for_windows_pkg"
repo = "Fndroid/clash_for_windows_pkg"
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/Fndroid/clash_for_windows_pkg/releases/download/{version}/Clash.for.Windows-{version}-win.7z",
    "https://github.com/Fndroid/clash_for_windows_pkg/releases/download/{version}/Clash.for.Windows.Setup.{version}.exe",
]

[[softwares]]
name = "clash"
repo = "Dreamacro/clash"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-linux-amd64-v{version}.gz",
    "https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-linux-amd64-v3-v{version}.gz",
    "https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-windows-amd64-v{version}.zip",
    "https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-windows-amd64-v3-v{version}.zip",
]

[[softwares]]
name = "ClashForAndroid"
repo = "Kr328/ClashForAndroid"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-foss-arm64-v8a-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-foss-armeabi-v7a-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-foss-universal-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-foss-x86-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-foss-x86_64-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-premium-arm64-v8a-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-premium-armeabi-v7a-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-premium-universal-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-premium-x86-release.apk",
    "https://github.com/Kr328/ClashForAndroid/releases/download/v{version}/cfa-{version}-premium-x86_64-release.apk",
]

[[softwares]]
name = "Clash.Meta"
repo = "MetaCubeX/Clash.Meta"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/MetaCubeX/Clash.Meta/releases/download/v{version}/clash.meta-linux-amd64-v{version}.gz",
    "https://github.com/MetaCubeX/Clash.Meta/releases/download/v{version}/clash.meta-linux-amd64-cgo-v{version}.gz",
    "https://github.com/MetaCubeX/Clash.Meta/releases/download/v{version}/clash.meta-windows-amd64-v{version}.zip",
    "https://github.com/MetaCubeX/Clash.Meta/releases/download/v{version}/clash.meta-windows-amd64-cgo-v{version}.zip",
]

[[softwares]]
name = "compose"
repo = "docker/compose"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/docker/compose/releases/download/v{version}/docker-compose-linux-x86_64",
    "https://github.com/docker/compose/releases/download/v{version}/docker-compose-windows-x86_64.exe",
]

[[softwares]]
name = "graalvm-ce-builds"
repo = "graalvm/graalvm-ce-builds"
tag_pattern = "^vm-ce-(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-{version}/graalvm-community-jdk-{version}_linux-x64_bin.tar.gz",
    "https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-{version}/graalvm-community-jdk-{version}_windows-x64_bin.zip",
]

[[softwares]]
name = "stonedb"
repo = "stoneatom/stonedb"
tag_pattern = "^5\\.7-v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))-GA$"
download_urls = [
    "https://github.com/stoneatom/stonedb/releases/download/5.7-v{version}-GA/stonedb-ce-5.7-v{version}.el7.x86_64.rpm",
    "https://github.com/stoneatom/stonedb/releases/download/5.7-v{version}-GA/stonedb-ce-5.7_v{version}.ubuntu.amd64.deb",
    "https://github.com/stoneatom/stonedb/releases/download/5.7-v{version}-GA/stonedb-ce-5.7-v{version}.el7.x86_64.tar.gz",
]

[[softwares]]
name = "libmaxminddb"
repo = "maxmind/libmaxminddb"
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/maxmind/libmaxminddb/releases/download/{version}/libmaxminddb-{version}.tar.gz",
]

[[softwares]]
name = "geoipupdate"
repo = "maxmind/geoipupdate"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/maxmind/geoipupdate/releases/download/v{version}/geoipupdate_{version}_linux_amd64.deb",
    "https://github.com/maxmind/geoipupdate/releases/download/v{version}/geoipupdate_{version}_linux_amd64.rpm",
    "https://github.com/maxmind/geoipupdate/releases/download/v{version}/geoipupdate_{version}_linux_amd64.tar.gz",
    "https://github.com/maxmind/geoipupdate/releases/download/v{version}/geoipupdate_{version}_windows_amd64.zip",
]

[[softwares]]
name = "upx"
repo = "upx/upx"
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-amd64_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-arm64_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-armeb_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-arm_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-dos.zip",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-i386_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-mipsel_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-mips_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-powerpc64le_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-powerpc_linux.tar.xz",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-win32.zip",
    "https://github.com/upx/upx/releases/download/v{version}/upx-{version}-win64.zip",
]

[[softwares]]
name = "curl"
repo = "curl/curl"
tag_pattern = "^curl-(?P<version>(?P<major>\\d+)_(?P<minor>\\d+)_(?P<patch>\\d+))$"
download_urls = [
    "https://curl.se/download/curl-{version}.tar.gz",
]

[[softwares]]
name = "libgd"
repo = "libgd/libgd"
tag_pattern = "^gd-(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://github.com/libgd/libgd/releases/download/gd-{version}/libgd-{version}.tar.gz",
]

[[softwares]]
name = "openssl"
repo = "openssl/openssl"
by_release = true
category = true
tag_pattern = "^OpenSSL (?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?P<suffix>[a-z])?)$"
download_urls = [
    "https://www.openssl.org/source/openssl-{version}.tar.gz",
]

[[softwares]]
name = "corretto-8"
repo = "corretto/corretto-8"
by_release = true
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)\\.(?P<suffix>\\d+))$"
download_urls = [
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-linux-x64.tar.gz",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64.msi",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64-jdk.zip",
]

[[softwares]]
name = "corretto-11"
repo = "corretto/corretto-11"
by_release = true
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)\\.(?P<suffix>\\d+)\\.(\\d+)?)$"
download_urls = [
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-linux-x64.tar.gz",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64.msi",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64-jdk.zip",
]

[[softwares]]
name = "corretto-17"
repo = "corretto/corretto-17"
by_release = true
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)\\.(?P<suffix>\\d+)\\.(\\d+)?)$"
download_urls = [
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-linux-x64.tar.gz",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64.msi",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64-jdk.zip",
]

[[softwares]]
name = "corretto-21"
repo = "corretto/corretto-21"
by_release = true
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)\\.(?P<suffix>\\d+)\\.(\\d+)?)$"
download_urls = [
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-linux-x64.tar.gz",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64.msi",
    "https://corretto.aws/downloads/resources/{version}/amazon-corretto-{version}-windows-x64-jdk.zip",
]

[[softwares]]
name = "python"
repo = "python/cpython"
category = true
tag_pattern = "^v(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://www.python.org/ftp/python/{version}/Python-{version}.tgz",
    "https://www.python.org/ftp/python/{version}/Python-{version}.tar.xz",
]

[[softwares]]
name = "php"
major = [7, 8]
category = true
parser = "PHPReleasesParser"
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://www.php.net/distributions/php-{version}.tar.gz",
]

[[softwares]]
name = "go"
category = true
parser = "GoReleasesParser"
tag_pattern = "^go(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://go.dev/dl/go{version}.src.tar.gz",
    "https://go.dev/dl/go{version}.linux-amd64.tar.gz",
    "https://go.dev/dl/go{version}.windows-amd64.msi",
    "https://go.dev/dl/go{version}.windows-amd64.msi",
]

[[softwares]]
name = "redis"
repo = "redis/redis"
by_release = true
category = true
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://download.redis.io/releases/redis-{version}.tar.gz",
]

[[softwares]]
name = "composer"
repo = "composer/composer"
by_release = true
category = true
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://getcomposer.org/download/{version}/composer.phar",
]

[[softwares]]
name = "httpd"
repo = "apache/httpd"
tag_pattern = "^(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://dlcdn.apache.org/httpd/httpd-{version}.tar.gz",
]

[[softwares]]
name = "nginx"
repo = "nginx/nginx"
tag_pattern = "^release-(?P<version>(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+))$"
download_urls = [
    "https://nginx.org/download/nginx-{version}.tar.gz",
]
